### ISSUE TITLE
Using http:// (not secure) url in secure website

### ISSUE THREAD

**Issue by ProxiBlue** [zipMoney/zip.magento1#70]
Hi,

This needs to be fixed.

Here:

https://github.com/zipMoney/zip.magento1/blob/439b25a92e2ef70431178f68b6573bd9d605d34e/src/app/code/community/Zip/Payment/etc/config.xml#L205

you are using a hard coded http:// request, which alerts customers in https:// checkout that site is potentially not secure, and directly affects sales on website, since clients back out of purchase.

![Selection_999(341)](https://user-images.githubusercontent.com/4994260/60491747-0dd03d80-9cdc-11e9-84b8-a772e641331f.png)

![Selection_999(340)](https://user-images.githubusercontent.com/4994260/60491780-23456780-9cdc-11e9-9fc4-1e6f66bc803f.png)

**Comment by benzhangzip** [comment]
Hi @ProxiBlue,
Thank you for reporting that issue, it is a typo on our end that should not use http, there is 2 options to fix this:
1. change http to https
https://d3k1w8lx8mqizo.cloudfront.net/INTEGRATIONS/2016/zippay/logos/zipPay-logo-onWhite.png

2. remove the http then it will use the same protocol as your server
//d3k1w8lx8mqizo.cloudfront.net/INTEGRATIONS/2016/zippay/logos/zipPay-logo-onWhite.png

We had already patched this in our development branches with other bug fixes and other feature enhancements, and we are doing some final testing and will push to Magento1 marketplace soon in 1-2 weeks (waiting approval from Magento)

Thanks again for finding the bug.
